### ISSUE TITLE
Modify speaker registration and representation

### ISSUE THREAD

**Issue by jandd** [devdaydresden/devday_website#24]
**Is your feature request related to a problem? Please describe.**
Currently a Speaker database entry is tied to an Attendee database entry and talks that were submitted by that speaker. This has a list of disadvantages:

- A new speaker instance is created when a speaker submits talks for a new event
- A speaker cannot decide to re-use existing biography and photographs
- Some speaker information is stored in the DevDayUser itself (name, organisation, ...) which leads to the issue that changes to these data will modify the Speaker representation for existing sessions by that speaker
- A user that has been a speaker in past events cannot be deleted without losing all information about his talks too 

**Describe the solution you'd like**
I would like to redesign the speaker registration process and entity model. There should be some kind of base speaker data (name, firstname, twitter handle, phone number, company/institution, job title, short biography, ...) that can be reused for new events if the speaker decides to do so. This information does not need to be tied to a specific event and thus Attendee entity.
When a talk submission of a speaker is accepted for an Event (by both the committee and the Speaker, which will lead to another feature request for talk states) a copy of the data that is relevant to display the Speaker for the current event to the audience should be made. This will lead to the nice effect that the speaker data will be frozen and will not change when the speaker changes personal data afterwards. An admin interface for changing such frozen speaker data will be required to fix typos or do modifications if there is some urgent personal/legal/other demand from the speaker or other relevant party. 

**Describe alternatives you've considered**
I thought about some kind of state for the speaker itself but this will not be sufficient to fix all of the disadvantages mentioned.

**Comment by stefanbethke** [comment]
Here's what I'd like to do:
* Create a new speaker object that serves as the speaker information for one or more talks
  * The speaker is optionally linked to a user who is allowed to edit this information
  * The speaker object contains all information that we'd like to display for a speaker: name, twitter, homepage, photo, company, position, bio.
  * When a talk is scheduled for an event, a copy of the speaker object is made and attached to the scheduled talk; the original speaker object stays connected to the user.
* All info that is currently kept in the DevDayUser is either moved to the new speaker object, or deleted. All we really need is email, password, account flags, and the date the user agreed to us keeping the info. No twitter handle, name or other info is necessary.

Registration for user accounts is open all the time, but registration as a speaker or attendee is limited according to the event flags.

When a speaker signs up, he or she can edit the existing speaker information; a new speaker object is created if one doesn't exist yet.

After the event is finished, all non-scheduled talks will be deleted.

If a user decides to close their account, or they do not confirm their agreement to continue to keep the data in the system, the user account and any potentially existing speaker object will be deleted. Since this speaker object is not connected to a scheduled talk, the schedule will remain the same.

**Comment by jandd** [comment]
Progress on the feature can be tracked in https://github.com/jandd/devday_website/tree/speaker-registration-and-representation-rework
